name: Deploy docs

on:
  push:
    branches:
      -DesignSystem

jobs:
  build-and-deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        width:
          node-version: 16

      - run: npm ci

      - run: npm run build

      - name: Deploy storybook
        working-directory: ./05-design-system/packages/docs
        run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}